version: '3.9'

services:
  backend:
    build: ./packages/backend
    ports:
      - 3000:3000
    volumes:
      - ./packages/backend/:/app/:ro
  
  frontend:
    build: ./packages/client
    ports:
      - 5000:5000
